const languages = [
	{ id: 1, name: "English", value: "en" },
	{ id: 2, name: "Spanish", value: "es" },
	{ id: 3, name: "French", value: "fr" },
	{ id: 4, name: "German", value: "de" },
	{ id: 5, name: "Chinese", value: "zh" },
	{ id: 6, name: "Japanese", value: "ja" },
	{ id: 7, name: "Korean", value: "ko" },
	{ id: 8, name: "Russian", value: "ru" },
	{ id: 9, name: "Italian", value: "it" },
	{ id: 10, name: "Portuguese", value: "pt" },
	{ id: 11, name: "Arabic", value: "ar" },
	{ id: 12, name: "Hindi", value: "hi" },
	{ id: 13, name: "Bengali", value: "bn" },
	{ id: 14, name: "Turkish", value: "tr" },
	{ id: 15, name: "Dutch", value: "nl" },
	{ id: 16, name: "Greek", value: "el" },
	{ id: 17, name: "Swedish", value: "sv" },
	{ id: 18, name: "Danish", value: "da" },
	{ id: 19, name: "Finnish", value: "fi" },
	{ id: 20, name: "Norwegian", value: "no" },
	{ id: 21, name: "Polish", value: "pl" },
	{ id: 22, name: "Czech", value: "cs" },
	{ id: 23, name: "Hungarian", value: "hu" },
	{ id: 24, name: "Romanian", value: "ro" },
	{ id: 25, name: "Thai", value: "th" },
	{ id: 26, name: "Vietnamese", value: "vi" },
	{ id: 27, name: "Indonesian", value: "id" },
	{ id: 28, name: "Hebrew", value: "he" },
	{ id: 29, name: "Malay", value: "ms" },
	{ id: 30, name: "Ukrainian", value: "uk" },
	{ id: 31, name: "Uzbek", value: "uz" },
];

export default languages;
